[package]
name = "valut"
version = "0.3.1"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
reqwest = { version = "0.13.5" }
anyhow = "1.0.104"
quick-xml = { version = "0.42.0", features = ["serde", "serialize"] }
chrono = "0.4.45"
rust_decimal = { version = "1.43.0", features = ["db-postgres"] }
sqlx = { version = "0.9.0", features = [
    "postgres",
    "runtime-tokio",
    "chrono",
    "macros",
    "rust_decimal",
    "uuid",
] }
dotenvy = "0.15.7"
uuid = "1.26.1"
log = "0.4.34"
env_logger = "0.11.11"
actix-web = "4.15.0"
